import { Data, IProductInput } from "@/types";
import { toSlug } from "./utils";

const products: IProductInput[] = [
  {
    id: 1, // Added ID
    name: "Classic White Tee",
    slug: toSlug("Classic White Tee"),
    category: "T-Shirts",
    images: ["/images/cloths/cloth.jpeg"],
    tags: ["new arrival"],
    isPublished: true,
    price: 20,
    listPrice: 25,
    brand: "Generic Brand",
    avgRating: 4.5,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 2 },
    ],
    numSales: 5,
    countInStock: 10,
    description: "A timeless classic, perfect for any casual outfit.",
    sizes: ["S", "M", "L"],
    colors: ["White"],
    reviews: [],
  },
  {
    id: 2, // Added ID
    name: "Black Leather Jacket",
    slug: toSlug("Black Leather Jacket"),
    category: "Jackets",
    images: ["/images/cloths/cloth1.jpeg"],
    tags: ["premium"],
    isPublished: true,
    price: 150,
    listPrice: 200,
    brand: "Fashion Co.",
    avgRating: 4.8,
    numReviews: 15,
    ratingDistribution: [
      { rating: 5, count: 12 },
      { rating: 4, count: 3 },
    ],
    numSales: 8,
    countInStock: 5,
    description: "Stylish and durable, this leather jacket is a must-have for your wardrobe.",
    sizes: ["M", "L", "XL"],
    colors: ["Black"],
    reviews: [],
  },
  {
    id: 3, // Added ID
    name: "Blue Denim Jeans",
    slug: toSlug("Blue Denim Jeans"),
    category: "Jeans",
    images: ["/images/cloths/cloth2.jpeg"],
    tags: ["casual"],
    isPublished: true,
    price: 50,
    listPrice: 60,
    brand: "Denim World",
    avgRating: 4.2,
    numReviews: 25,
    ratingDistribution: [
      { rating: 5, count: 18 },
      { rating: 4, count: 7 },
    ],
    numSales: 12,
    countInStock: 20,
    description: "Comfortable and versatile, these jeans are perfect for everyday wear.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue"],
    reviews: [],
  },
  {
    id: 4, // Added ID
    name: "Red Plaid Shirt",
    slug: toSlug("Red Plaid Shirt"),
    category: "Shirts",
    images: ["/images/cloths/cloth3.jpeg"],
    tags: ["trendy"],
    isPublished: true,
    price: 35,
    listPrice: 40,
    brand: "Trendy Wear",
    avgRating: 4.0,
    numReviews: 20,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 10 },
    ],
    numSales: 10,
    countInStock: 15,
    description: "A bold and trendy shirt that adds a pop of color to your outfit.",
    sizes: ["S", "M", "L"],
    colors: ["Red"],
    reviews: [],
  },
  {
    id: 5, // Added ID
    name: "Gray Hoodie",
    slug: toSlug("Gray Hoodie"),
    category: "Hoodies",
    images: ["/images/cloths/cloth4.jpeg"],
    tags: ["comfort"],
    isPublished: true,
    price: 45,
    listPrice: 50,
    brand: "Cozy Wear",
    avgRating: 4.7,
    numReviews: 30,
    ratingDistribution: [
      { rating: 5, count: 25 },
      { rating: 4, count: 5 },
    ],
    numSales: 15,
    countInStock: 12,
    description: "Soft and cozy, this hoodie is perfect for chilly days.",
    sizes: ["S", "M", "L", "XL"],
    colors: ["Gray"],
    reviews: [],
  },
  {
    id: 6, // Added ID
    name: "Striped Summer Dress",
    slug: toSlug("Striped Summer Dress"),
    category: "Dresses",
    images: ["/images/cloths/cloth5.jpeg"],
    tags: ["summer"],
    isPublished: true,
    price: 60,
    listPrice: 70,
    brand: "Summer Style",
    avgRating: 4.6,
    numReviews: 18,
    ratingDistribution: [
      { rating: 5, count: 15 },
      { rating: 4, count: 3 },
    ],
    numSales: 7,
    countInStock: 8,
    description: "Light and breezy, this dress is ideal for summer outings.",
    sizes: ["S", "M"],
    colors: ["Blue", "White"],
    reviews: [],
  },
  {
    id: 7, // Added ID
    name: "Brown Suede Boots",
    slug: toSlug("Brown Suede Boots"),
    category: "Footwear",
    images: ["/images/cloths/cloth6.jpeg"],
    tags: ["premium"],
    isPublished: true,
    price: 120,
    listPrice: 150,
    brand: "Boots & Co.",
    avgRating: 4.4,
    numReviews: 22,
    ratingDistribution: [
      { rating: 5, count: 18 },
      { rating: 4, count: 4 },
    ],
    numSales: 9,
    countInStock: 6,
    description: "Elegant and durable, these boots are perfect for any season.",
    sizes: ["8", "9", "10"],
    colors: ["Brown"],
    reviews: [],
  },
  {
    id: 8, // Added ID
    name: "Green Parka Jacket",
    slug: toSlug("Green Parka Jacket"),
    category: "Jackets",
    images: ["/images/cloths/cloth7.jpeg"],
    tags: ["winter"],
    isPublished: true,
    price: 180,
    listPrice: 200,
    brand: "Outdoor Gear",
    avgRating: 4.3,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
    ],
    numSales: 6,
    countInStock: 4,
    description: "Stay warm and stylish with this waterproof parka jacket.",
    sizes: ["M", "L", "XL"],
    colors: ["Green"],
    reviews: [],
  },
  {
    id: 9, // Added ID
    name: "White Sneakers",
    slug: toSlug("White Sneakers"),
    category: "Footwear",
    images: ["/images/cloths/cloth8.jpeg"],
    tags: ["casual"],
    isPublished: true,
    price: 80,
    listPrice: 100,
    brand: "Sneaker World",
    avgRating: 4.9,
    numReviews: 40,
    ratingDistribution: [
      { rating: 5, count: 35 },
      { rating: 4, count: 5 },
    ],
    numSales: 20,
    countInStock: 15,
    description: "Comfortable and trendy, these sneakers go with any outfit.",
    sizes: ["7", "8", "9", "10"],
    colors: ["White"],
    reviews: [],
  },
  {
    id: 10, // Added ID
    name: "Pink Scarf",
    slug: toSlug("Pink Scarf"),
    category: "Accessories",
    images: ["/images/cloths/cloth9.jpeg"],
    tags: ["winter"],
    isPublished: true,
    price: 15,
    listPrice: 20,
    brand: "Winter Comfort",
    avgRating: 4.1,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
    ],
    numSales: 5,
    countInStock: 25,
    description: "A soft and warm scarf to keep you cozy in winter.",
    sizes: ["One Size"],
    colors: ["Pink"],
    reviews: [],
  },
  {
    id: 11, // Added ID
    name: "Pink Scarf",
    slug: toSlug("Pink Scarf 2"),
    category: "Accessories",
    images: ["/images/cloths/cloth10.jpeg"],
    tags: ["winter"],
    isPublished: true,
    price: 15,
    listPrice: 20,
    brand: "Winter Comfort",
    avgRating: 4.1,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
    ],
    numSales: 5,
    countInStock: 25,
    description: "A soft and warm scarf to keep you cozy in winter.",
    sizes: ["One Size"],
    colors: ["Pink"],
    reviews: [],
  },
];

const data: Data = {
  products,
  headerMenus: [],
  carousels: [],
  settings: [],
};

export type { IProductInput };
export { products };
export default data;